# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc49c1dc60a8b57aa39b96f6bbe771ed94fe5f08dd227e475f13983f7381289d2703a1527b999351944c5e7dfad3d644c11320a595f92690506e6148c4f7d5d1

test:
  secret_key_base: e84c73e2ff1563a9ac3199023f49624edc62e55dee391c355e0e09edb28d659e35198489ffc75bc4c0bbb420bc13fafd9a9e094087275aea7ce4a289bc40adaa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
